// <auto-generated />
using ConfigFactory.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ConfigFactory.Migrations
{
    [DbContext(typeof(UsersContext))]
    [Migration("20240204004625_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.26");

            modelBuilder.Entity("ConfigFactory.DAL.Entities.UserConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ConfigCategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConfigName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("ConfigValue")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("UserConfigs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ConfigCategoryId = 1,
                            ConfigName = "PO_Prefix",
                            ConfigValue = "TR-",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            ConfigCategoryId = 1,
                            ConfigName = "SerialNumbersAreRequired",
                            ConfigValue = "true",
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            ConfigCategoryId = 1,
                            ConfigName = "ForecastCadence",
                            ConfigValue = "1",
                            UserId = 1
                        },
                        new
                        {
                            Id = 4,
                            ConfigCategoryId = 1,
                            ConfigName = "FrozenPeriodWeeks",
                            ConfigValue = "2",
                            UserId = 1
                        },
                        new
                        {
                            Id = 5,
                            ConfigCategoryId = 1,
                            ConfigName = "PO_Prefix",
                            ConfigValue = "US",
                            UserId = 2
                        },
                        new
                        {
                            Id = 6,
                            ConfigCategoryId = 1,
                            ConfigName = "SerialNumbersAreRequired",
                            ConfigValue = "false",
                            UserId = 2
                        },
                        new
                        {
                            Id = 7,
                            ConfigCategoryId = 1,
                            ConfigName = "ForecastCadence",
                            ConfigValue = "2",
                            UserId = 2
                        },
                        new
                        {
                            Id = 8,
                            ConfigCategoryId = 1,
                            ConfigName = "FrozenPeriodWeeks",
                            ConfigValue = "1",
                            UserId = 2
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
